### ISSUE TITLE
Preferred Citation?

### ISSUE THREAD

**Issue by augustfly** [caseyjlaw/rtpipe#12]
hi there, I'm a data scientist for the AAS Journals (ApJ/AJ). I was wondering if[ Law et al. (2015)](https://doi.org/10.1088/0004-637X/807/1/16) is the preferred citation for this code? That is what I've seen in submitted manuscripts, but I've made it a habit of mine to check with author's at their source repositories to confirm this if it isn't stated explicitly on the project's github landing page.

thanks.

**Comment by caseyjlaw** [comment]
Yes, that is the preferred citation. We are working on a new publication, but that will do for now. Thanks.
